redis:
  image: redis:latest
  volumes:
    - /var/lib/redis
  ports:
    - "6379"

mongo:
  image: sameersbn/mongodb:latest
  ports:
    - "27017:27017"
  volumes:
    - /srv/docker/mongodb:/var/lib/mongodb
  restart: always

web:
  build: .
  restart: always
  ports:
    - "8000:8000"
  links:
    - redis
    - mongo
